- name: Copy Intake24 root CA certificate
  copy: src={{ java_options.internal_ca_certificate_path }} dest=/tmp/ca.cert.pem

- name: Find currently active JRE
  shell: "update-alternatives --query java | grep 'Value:' | sed -e 's/Value: \\(.*\\)\\/bin\\/java/\\1/'"
  register: update_alternatives_result

- name: Set JRE path
  set_fact: active_jre_directory={{update_alternatives_result.stdout}}

- name: Remove existing root CA certificate from Java keystore
  shell: "keytool -delete -noprompt -storepass changeit -alias Intake24RootCA -keystore {{active_jre_directory}}/lib/security/cacerts"
  failed_when: false

- name: Add root CA certificate to Java keystore
  shell: "keytool -import -trustcacerts -noprompt -storepass changeit -file /tmp/ca.cert.pem -alias Intake24RootCA -keystore {{active_jre_directory}}/lib/security/cacerts"
