- name: Install required extensions
  command: /usr/bin/psql -U {{postgres_admin_user}} -c "create extension if not exists \"{{item}}\";"
  with_items:
   - uuid-ossp

- name: Create system database
  command: /usr/bin/createdb -U {{postgres_admin_user}} --owner={{intake24_database_user}} {{system_database_name}}

- name: Upload database snapshot (schema)
  copy: src={{schema_snapshot_path}} dest=/home/deploy/intake24_system_schema.pgcustom

- name: Upload database snapshot (constants)
  copy: src={{data_snapshot_path}} dest=/home/deploy/intake24_system_data.pgcustom

- name: Restore database snapshot (schema)
  command: /usr/bin/pg_restore -U {{postgres_admin_user}} -n public --no-owner --no-acl --role=intake24 --dbname {{system_database_name}} /home/deploy/intake24_system_schema.pgcustom

- name: Restore database snapshot (constants)
  command: /usr/bin/pg_restore -U {{postgres_admin_user}} -n public --no-owner --no-acl --role=intake24 --dbname {{system_database_name}} /home/deploy/intake24_system_data.pgcustom

- name: Delete snapshots
  file:
    path: "{{item}}"
  with_items:
    - /home/deploy/intake24_system_schema.pgcustom
    - /home/deploy/intake24_system_data.pgcustom
  
- name: Create default Intake24 admin user
  command: /usr/bin/psql -U {{postgres_admin_user}} -d {{system_database_name}} -c "{{item}}"
  with_items:
  - >
     INSERT INTO users(name, email, phone, simple_name, email_notifications, sms_notifications) VALUES ('Intake24 Admin', '{{admin_user_email}}', null, 'intake24 admin', true, true);
     INSERT INTO user_passwords (user_id, password_hash, password_salt, password_hasher) VALUES (1, 'hU+SnrQ/+uAxfPyvpqCw9vixHzwC2Ph/Zqasd6CLgrE=', 'DWXIWvxIVfX1vBYfASmy0A==','shiro-sha256');
     INSERT INTO user_roles(user_id, role) VALUES (1, 'superuser');
