- name: Make sure Git is installed
  become: yes
  apt:
    update-cache: yes
    cache_valid_time: 86400
    name: git
    state: present

- name: Make sure .ssh directory exists for intake24-admin
  become: yes
  file:
    name: /home/{{ app.name }}/.ssh
    state: directory
    owner: "{{ app.name }}"
    group: "{{ app.name }}"

- name: Make sure application directory exists
  become: yes
  file:
    path: "{{ app.directory }}"
    state: directory
    owner: "{{ app.name }}"
    group: "{{ app.name }}"

- name: Checkout source from Git repository
  become: yes
  become_user: "{{ app.name }}"
  git:
    repo: "{{ git.repository_url }}"
    dest: "{{ app.directory}}"
    version: "{{ git.branch_name }}"
    force: yes
    accept_hostkey: true
