- name: Make sure Git is installed
  become: yes
  apt:
    update-cache: yes
    cache_valid_time: 86400
    name: git
    state: present

- name: Make sure .ssh directory exists for intake24-admin
  become: yes
  file: name=/home/intake24-admin/.ssh state=directory owner=intake24-admin group=intake24-admin

- name: Make sure application directory exists
  become: yes
  file: path={{ app.directory }} state=directory owner=intake24-admin group=intake24-admin

- name: Checkout source from Git repository
  become: yes
  become_user: intake24-admin
  git:
    repo: "{{ git.repository_url }}"
    dest: "{{ app.directory}}"
    version: "{{git.branch_name}}"
    force: yes
    accept_hostkey: true
